version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: DAC_POSTGRES_DB
    environment:
      POSTGRES_USER: dac
      POSTGRES_PASSWORD: dac_pwd
      POSTGRES_DB: dac_db
    ports:
      - "5450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
