server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5450/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
